### ISSUE TITLE
RecommendNextComponents Should Return MetaTypes Rather than PySpice Types.

### ISSUE THREAD

**Issue by umesh-timalsina** [symbench/electric-circuits#111]
It might be nice to map recommend results of recommend next components to `MetaType` when running the plugin rather than PySpice Types.

**Comment by umesh-timalsina** [comment]
This will be helpful for displaying recommendations in the ElectricCircuitsVisualizer.

**Comment by brollb** [comment]
I think this sounds good but I would add this as a post-processing step after the individual model is used (similar to how sorting is currently handled).

**Comment by umesh-timalsina** [comment]
Yeah. This step should be agnostic of the model used, some components (Like `DCTransmissionLine`) might be missing in the metamodel, which would be a nice check to have.
