### ISSUE TITLE
Example Component Recommender Analytic

### ISSUE THREAD

**Issue by brollb** [symbench/electric-circuits#63]
As a concrete example of an analytic (referenced generally in #59), it would be nice to add a component recommender/completer to make sure everything is in place so we can experiment with models trained from https://github.com/symbench/spice-completion/.

For the purposes of this issue, the "mock" recommender could simply return the top 3 most commonly used components in the netlist. Concretely, it might be nice to have the mock recommender use the netlist representation (not the GME nodes) and return the top three components with confidences (probably just some hard-coded values for the mock analytic).

**Comment by umesh-timalsina** [comment]
@brollb Thanks. This makes sense to me. I will get started on this mockup plugin.
