### ISSUE TITLE
Default plugins for metanodes

### ISSUE THREAD

**Issue by brollb** [symbench/electric-circuits#81]
I noticed that it appears that `CreateElectricCircuitsMeta` is enabled by default on `Circuit` nodes which seems a bit counterintuitive - I would expect it to only be enabled on the "language container" (ie, `ElectricCircuits` in the root node).

It would also be nice if 
- the recommendation plugin was enabled by default on circuits
- the export plugin was enabled by default on circuits
- the import plugin was enabled on circuit folders

**Comment by umesh-timalsina** [comment]
`JSONImporter` is now available as a standalone Repository at [deepforge-dev/webgme-json-importer](https://github.com/deepforge-dev/webgme-json-importer). The library should be used instead of copied code from `deepforge-keras`. While resolving this.
